language: python
python: "2.7"

branches:
  only:
  - master
  - /^feature\/.*$/
  - /^bugfix\/.*$/

# command to install dependencies
addons:
  chrome: stable

install:
  - pip install -r requirements.txt
  - bash dependency.sh

# command to run tests
script:
  - bash test.sh


  